### PR TITLE
Husky

### PR DESCRIPTION
**Pull request by DNaunin**
- Add Husky and lint-staged
     https://typicode.github.io/husky/#/
     https://github.com/okonet/lint-staged
- Add test, typecheck, prettycheck to package.json scripts
- Add husky/pre-push

### CODE REVIEW

**Review by fre-ben — APPROVED** [review]
GJ 💯 
You could add the links to husky etc. to the description :)

**Review by christophvogel — APPROVED** [review]
LGTM 👍

**Review by JuKahl — APPROVED** [review]
GJ 🚀

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Pull request merged**
