### PR TITLE
Add ESLint

### PR DESCRIPTION
**Pull request by DNaunin**
• Add Types to .hello.ts
• Add Types to ._app.tsx

### CODE REVIEW

**Review by saschahaselhuhn — APPROVED** [review]
gj

**Review by m-wiemers — APPROVED** [review]
that I may still experience this 👁‍🗨👁‍🗨

**Review by phlgr — CHANGES_REQUESTED** [review]
GJ, but the eslint script is missing

**Comment by HorstFrank** [comment]
gj. i don't miss the eslint script : D:D

**Review by mrana17 — APPROVED** [review]
gj 👍

**Pull request merged**
