### PR TITLE
✨ Add custom server

### PR DESCRIPTION
**Pull request by DNaunin**
Add server folder
Run npm i -D nodemon ts-node
Add tsconfig.server.json for a custom TypeScript config for the server side
Add nodemon.json to configure nodemon. The server folder is watched.
Add and update dev, build-next, build-server, build and start scripts.

### CODE REVIEW

**Review by fgottesmann — APPROVED** [review]
lgtm :)

**Review by christophvogel — APPROVED** [review]
GJ 💯

**Review by m-wiemers — APPROVED** [review]
A master of her craft

**Review by RonjaMeinecke — APPROVED** [review]
well done 👊🏼

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Comment by SilviaBarcellini** [comment]
All very good! 👍

**Pull request merged**
